# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def solver(max):
  sum = 0
  term_1 = 0
  term_2 = 1

  while term_2 < max:
    next_term = term_1 + term_2
    if next_term % 2 == 0:
      sum += next_term
    term_1 = term_2
    term_2 = next_term

  print(sum)

solver(4000000)
